name: Inspector build

on:
  push:
    branches: [ main ]
    paths:
      - 'tools/inspector/**'
      - 'renderers/lit/**'
      - '.github/workflows/inspector_build.yml'
  pull_request:
    paths:
      - 'tools/inspector/**'
      - 'renderers/lit/**'
      - '.github/workflows/inspector_build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install lib's deps
        working-directory: ./renderers/lit
        run: npm ci

      - name: Build lib
        working-directory: ./renderers/lit
        run: npm run build

      - name: Install inspector deps
        working-directory: ./tools/inspector
        run: npm install

      - name: Build inspector
        working-directory: ./tools/inspector
        run: npm run build
