name: Angular build and test

on:
  push:
    branches: [ main ]
    paths:
      - 'angular/**'
      - 'web/lib/**'
  pull_request:
    paths:
      - 'angular/**'
      - 'web/lib/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install top-level deps
        working-directory: ./angular
        run: npm ci

      - name: Install lib deps
        working-directory: ./angular/projects/lib
        run: npm i

      - name: Build lib
        working-directory: ./angular
        run: npm run build lib
