name: Build python samples

on:
  push:
    branches:
      - main
    paths:
      - 'samples/agent/adk/**'
      - 'a2a_agents/python/a2ui_extension/**'
  pull_request:
    paths:
      - 'samples/agent/adk/**'
      - 'a2a_agents/python/a2ui_extension/**'

jobs:
  build:
    name: Build samples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install `uv` globally
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Build contact_lookup
        working-directory: samples/agent/adk/contact_lookup
        run: uv build .

      - name: Build orchestrator
        working-directory: samples/agent/adk/orchestrator
        run: uv build .

      - name: Build restaurant_finder
        working-directory: samples/agent/adk/restaurant_finder
        run: uv build .

      - name: Build rizzcharts
        working-directory: samples/agent/adk/rizzcharts
        run: uv build .
