name: Web (Lit) build and test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install editor deps
        working-directory: ./editor
        run: npm ci

      - name: Install all deps
        working-directory: ./samples/client/lit
        run: npm install --workspaces

      - name: Build all workspaces
        working-directory: ./samples/client/lit
        run: npm run build --workspaces

      - name: Run all tests
        working-directory: ./samples/client/lit
        run: npm run test --workspace=tests
